/* eslint-disable no-template-curly-in-string */

// Shared curl + jq block that fetches decrypted secrets into KEY/VALUE TSV rows
function fetchSecretsScript(indent = "          "): string[] {
  const i = indent
  return [
    `${i}set -euo pipefail`,
    "",
    `${i}HTTP_CODE=$(curl -s -o /tmp/wk_response.json -w "%{http_code}" \\`,
    `${i}  -H "Authorization: Bearer \${WINDKEEP_TOKEN}" \\`,
    `${i}  "\${WINDKEEP_URL}/api/projects/\${WINDKEEP_PROJECT_ID}/secrets")`,
    "",
    `${i}if [ "$HTTP_CODE" != "200" ]; then`,
    `${i}  echo "HTTP \${HTTP_CODE}:" && cat /tmp/wk_response.json`,
    `${i}  exit 1`,
    `${i}fi`,
    "",
    `${i}RESPONSE=$(cat /tmp/wk_response.json)`,
  ]
}

const windkeepSecrets: IntegrationSecretVar[] = [
  {
    name: "WINDKEEP_URL",
    description: "Public base URL of your WindKeep instance (no trailing slash).",
    source: "baseURL",
  },
  {
    name: "WINDKEEP_PROJECT_ID",
    description: "This project's ID — used in the secrets API path.",
    source: "projectId",
  },
  {
    name: "WINDKEEP_TOKEN",
    description: "Service token with access to the environments you want synced (Bearer st_…).",
    source: "serviceToken",
    placeholder: "Generate below, then paste into your secrets store",
  },
]

export const INTEGRATIONS: IntegrationDefinition[] = [
  {
    id: "railway",
    name: "Railway",
    summary: "Sync secrets into a Railway service and deploy from GitHub Actions.",
    description: "On every push to main, GitHub Actions pulls decrypted secrets from WindKeep with a service token, writes them to your Railway service with the Railway CLI, then deploys.",
    icon: "simple-icons:railway",
    docsUrl: "https://docs.railway.com/guides/cli",
    docsLabel: "Railway CLI docs",
    secretsHeading: "GitHub Actions secrets",
    secretsHint: "Add these under your repository → Settings → Secrets and variables → Actions.",
    snippetHeading: "Workflow file",
    defaultTokenName: "Railway Deploy",
    defaultEnvironments: ["PRODUCTION"],
    tokenHint: "Generate a token scoped for this integration. Copy it into the WINDKEEP_TOKEN GitHub secret.",
    steps: [
      {
        title: "Create a WindKeep service token",
        body: "Generate a token scoped to the environments you want Railway to receive (typically Production). Copy it once — it will not be shown again.",
      },
      {
        title: "Create a Railway API token",
        body: "In Railway → Account Settings → Tokens, create a token with access to the target project. Store it as RAILWAY_TOKEN in GitHub Actions secrets.",
      },
      {
        title: "Add GitHub Actions secrets",
        body: "In your repo → Settings → Secrets and variables → Actions, add the variables listed below. Project ID and WindKeep URL can be copied from this sheet.",
      },
      {
        title: "Commit the workflow",
        body: "Add the workflow file to .github/workflows/. On the next push to main, secrets sync to Railway and the service deploys.",
      },
    ],
    secrets: [
      ...windkeepSecrets,
      {
        name: "RAILWAY_TOKEN",
        description: "Railway account or project token used by the CLI.",
        placeholder: "From Railway → Account Settings → Tokens",
      },
      {
        name: "RAILWAY_SERVICE",
        description: "Name of the Railway service that should receive the variables.",
        placeholder: "e.g. web, api, windkeep",
      },
    ],
    buildSnippet: ({ baseURL, projectId }) => ({
      filename: ".github/workflows/deploy.yml",
      language: "yml",
      code: [
        "name: Deploy to Railway",
        "",
        "on:",
        "  push:",
        "    branches: [main]",
        "",
        "jobs:",
        "  deploy:",
        "    runs-on: ubuntu-latest",
        "",
        "    steps:",
        "      - uses: actions/checkout@v4",
        "",
        "      - name: Install Railway CLI",
        "        run: npm install -g @railway/cli",
        "",
        "      - name: Sync secrets",
        "        env:",
        "          WINDKEEP_URL: ${{ secrets.WINDKEEP_URL }}",
        "          WINDKEEP_PROJECT_ID: ${{ secrets.WINDKEEP_PROJECT_ID }}",
        "          WINDKEEP_TOKEN: ${{ secrets.WINDKEEP_TOKEN }}",
        "          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}",
        "          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE }}",
        "        run: |",
        ...fetchSecretsScript(),
        "",
        "          VARS_ARGS=()",
        String.raw`          while IFS=$'\t' read -r KEY VALUE; do`,
        "            echo \"::add-mask::${VALUE}\"",
        "            VARS_ARGS+=(\"${KEY}=${VALUE}\")",
        "          done < <(echo \"$RESPONSE\" | jq -r '",
        "            .decryptedSecrets[] | . as $s | .values[] | [($s.key | ascii_upcase), .value] | @tsv",
        "          ')",
        "",
        "          if [ ${#VARS_ARGS[@]} -eq 0 ]; then",
        "            echo \"No secrets returned.\" && exit 1",
        "          fi",
        "",
        "          railway variables set \"${VARS_ARGS[@]}\" --service \"$RAILWAY_SERVICE\"",
        "",
        "      - name: Deploy to Railway",
        "        env:",
        "          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}",
        "          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE }}",
        "        run: |",
        "          railway up --detach --service \"$RAILWAY_SERVICE\"",
        "",
        `# Project: ${projectId}`,
        `# WindKeep: ${baseURL}`,
      ].join("\n"),
    }),
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    summary: "Inject secrets into CI jobs from the WindKeep secrets API.",
    description: "Fetch decrypted secrets with a service token and export them into GITHUB_ENV so later steps can build, test, or deploy without committing env files.",
    icon: "simple-icons:githubactions",
    docsUrl: "https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions",
    docsLabel: "GitHub Actions secrets docs",
    secretsHeading: "GitHub Actions secrets",
    secretsHint: "Add these under your repository → Settings → Secrets and variables → Actions.",
    snippetHeading: "Workflow file",
    defaultTokenName: "GitHub Actions CI",
    defaultEnvironments: ["PRODUCTION"],
    tokenHint: "Generate a token scoped for this integration. Copy it into the WINDKEEP_TOKEN GitHub secret.",
    steps: [
      {
        title: "Create a WindKeep service token",
        body: "Generate a token scoped to the environments your CI job needs (typically Production). Copy it once — it will not be shown again.",
      },
      {
        title: "Add GitHub Actions secrets",
        body: "In your repo → Settings → Secrets and variables → Actions, add WINDKEEP_URL, WINDKEEP_PROJECT_ID, and WINDKEEP_TOKEN. Values can be copied from this sheet.",
      },
      {
        title: "Add the fetch step",
        body: "Commit the workflow below (or paste the Fetch WindKeep secrets step into an existing workflow). Secrets are masked and written to GITHUB_ENV for subsequent steps.",
      },
      {
        title: "Use secrets in later steps",
        body: "Any step after the fetch step can read the injected variables as normal environment variables (e.g. $DATABASE_URL).",
      },
    ],
    secrets: windkeepSecrets.map(s =>
      s.name === "WINDKEEP_TOKEN"
        ? { ...s, placeholder: "Generate below, then paste into GitHub Secrets" }
        : s,
    ),
    buildSnippet: ({ baseURL, projectId, projectSlug }) => ({
      filename: ".github/workflows/ci.yml",
      language: "yml",
      code: [
        "name: CI with WindKeep secrets",
        "",
        "on:",
        "  push:",
        "    branches: [main]",
        "  pull_request:",
        "",
        "jobs:",
        "  build:",
        "    runs-on: ubuntu-latest",
        "",
        "    steps:",
        "      - uses: actions/checkout@v4",
        "",
        "      - name: Fetch WindKeep secrets",
        "        env:",
        "          WINDKEEP_URL: ${{ secrets.WINDKEEP_URL }}",
        "          WINDKEEP_PROJECT_ID: ${{ secrets.WINDKEEP_PROJECT_ID }}",
        "          WINDKEEP_TOKEN: ${{ secrets.WINDKEEP_TOKEN }}",
        "        run: |",
        ...fetchSecretsScript(),
        "",
        String.raw`          while IFS=$'\t' read -r KEY VALUE; do`,
        "            echo \"::add-mask::${VALUE}\"",
        "            {",
        "              echo \"${KEY}<<EOF\"",
        "              echo \"${VALUE}\"",
        "              echo \"EOF\"",
        "            } >> \"$GITHUB_ENV\"",
        "          done < <(echo \"$RESPONSE\" | jq -r '",
        "            .decryptedSecrets[] | . as $s | .values[] | [($s.key | ascii_upcase), .value] | @tsv",
        "          ')",
        "",
        "      - name: Build",
        "        run: |",
        "          # Secrets from WindKeep are available as env vars here",
        "          npm ci",
        "          npm run build",
        "",
        `# Project: ${projectSlug} (${projectId})`,
        `# WindKeep: ${baseURL}`,
      ].join("\n"),
    }),
  },
  {
    id: "vercel",
    name: "Vercel",
    summary: "Push project secrets into Vercel environment variables.",
    description: "On every push to main, GitHub Actions pulls decrypted secrets from WindKeep and upserts them into your Vercel project with the Vercel CLI, then triggers a production deploy.",
    icon: "simple-icons:vercel",
    docsUrl: "https://vercel.com/docs/cli/env",
    docsLabel: "Vercel CLI env docs",
    secretsHeading: "GitHub Actions secrets",
    secretsHint: "Add these under your repository → Settings → Secrets and variables → Actions.",
    snippetHeading: "Workflow file",
    defaultTokenName: "Vercel Sync",
    defaultEnvironments: ["PRODUCTION"],
    tokenHint: "Generate a token scoped for this integration. Copy it into the WINDKEEP_TOKEN GitHub secret.",
    steps: [
      {
        title: "Create a WindKeep service token",
        body: "Generate a token scoped to the environments you want Vercel to receive (typically Production). Copy it once — it will not be shown again.",
      },
      {
        title: "Create a Vercel token",
        body: "In Vercel → Account Settings → Tokens, create a token with access to the target team/project. Store it as VERCEL_TOKEN. Also copy the Org ID and Project ID from the project settings.",
      },
      {
        title: "Add GitHub Actions secrets",
        body: "In your repo → Settings → Secrets and variables → Actions, add the variables listed below. WindKeep values can be copied from this sheet.",
      },
      {
        title: "Commit the workflow",
        body: "Add the workflow file to .github/workflows/. On the next push to main, secrets sync to Vercel Production and a deploy is triggered.",
      },
    ],
    secrets: [
      ...windkeepSecrets,
      {
        name: "VERCEL_TOKEN",
        description: "Vercel personal or team token used by the CLI.",
        placeholder: "From Vercel → Account Settings → Tokens",
      },
      {
        name: "VERCEL_ORG_ID",
        description: "Vercel team/org ID (VERCEL_ORG_ID in project settings).",
        placeholder: "team_…",
      },
      {
        name: "VERCEL_PROJECT_ID",
        description: "Vercel project ID (VERCEL_PROJECT_ID in project settings).",
        placeholder: "prj_…",
      },
    ],
    buildSnippet: ({ baseURL, projectId }) => ({
      filename: ".github/workflows/sync-vercel-env.yml",
      language: "yml",
      code: [
        "name: Sync secrets to Vercel",
        "",
        "on:",
        "  push:",
        "    branches: [main]",
        "",
        "jobs:",
        "  sync:",
        "    runs-on: ubuntu-latest",
        "",
        "    steps:",
        "      - uses: actions/checkout@v4",
        "",
        "      - name: Install Vercel CLI",
        "        run: npm install -g vercel",
        "",
        "      - name: Sync secrets to Vercel",
        "        env:",
        "          WINDKEEP_URL: ${{ secrets.WINDKEEP_URL }}",
        "          WINDKEEP_PROJECT_ID: ${{ secrets.WINDKEEP_PROJECT_ID }}",
        "          WINDKEEP_TOKEN: ${{ secrets.WINDKEEP_TOKEN }}",
        "          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}",
        "          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}",
        "          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}",
        "        run: |",
        ...fetchSecretsScript(),
        "",
        String.raw`          while IFS=$'\t' read -r KEY VALUE; do`,
        "            echo \"::add-mask::${VALUE}\"",
        "            vercel env rm \"$KEY\" production -y >/dev/null 2>&1 || true",
        "            printf '%s' \"$VALUE\" | vercel env add \"$KEY\" production",
        "          done < <(echo \"$RESPONSE\" | jq -r '",
        "            .decryptedSecrets[] | . as $s | .values[] | [($s.key | ascii_upcase), .value] | @tsv",
        "          ')",
        "",
        "      - name: Deploy to Vercel",
        "        env:",
        "          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}",
        "          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}",
        "          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}",
        "        run: vercel deploy --prod --yes",
        "",
        `# Project: ${projectId}`,
        `# WindKeep: ${baseURL}`,
      ].join("\n"),
    }),
  },
  {
    id: "docker",
    name: "Docker Compose",
    summary: "Pull secrets into a local or CI Compose stack.",
    description: "A small script fetches decrypted secrets with a service token, writes an env file, and starts your Compose stack with --env-file so containers never need committed .env files.",
    icon: "simple-icons:docker",
    docsUrl: "https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/",
    docsLabel: "Compose env docs",
    secretsHeading: "Required variables",
    secretsHint: "Export these in your shell, or store them in CI secrets before running the script.",
    snippetHeading: "Pull script",
    defaultTokenName: "Docker Compose",
    defaultEnvironments: ["DEVELOPMENT"],
    tokenHint: "Generate a token scoped for this integration. Export it as WINDKEEP_TOKEN before running the script.",
    steps: [
      {
        title: "Create a WindKeep service token",
        body: "Generate a token scoped to the environments your Compose stack needs (typically Development for local work). Copy it once — it will not be shown again.",
      },
      {
        title: "Export WindKeep variables",
        body: "Set WINDKEEP_URL, WINDKEEP_PROJECT_ID, and WINDKEEP_TOKEN in your shell (or CI). Values can be copied from this sheet.",
      },
      {
        title: "Add the pull script",
        body: "Save the script below as scripts/windkeep-compose.sh (or similar) and make it executable. It writes .env.windkeep and runs docker compose.",
      },
      {
        title: "Reference the env file",
        body: "Point services at the generated file with env_file: .env.windkeep in compose.yaml, or rely on --env-file for Compose variable substitution.",
      },
    ],
    secrets: windkeepSecrets.map(s =>
      s.name === "WINDKEEP_TOKEN"
        ? { ...s, placeholder: "Generate below, then export as WINDKEEP_TOKEN" }
        : s,
    ),
    buildSnippet: ({ baseURL, projectId, projectSlug }) => ({
      filename: "scripts/windkeep-compose.sh",
      language: "bash",
      code: [
        "#!/usr/bin/env bash",
        `# Pull WindKeep secrets for ${projectSlug} and start Compose`,
        "set -euo pipefail",
        "",
        ": \"${WINDKEEP_URL:?Set WINDKEEP_URL}\"",
        ": \"${WINDKEEP_PROJECT_ID:?Set WINDKEEP_PROJECT_ID}\"",
        ": \"${WINDKEEP_TOKEN:?Set WINDKEEP_TOKEN}\"",
        "",
        "ENV_FILE=\"${ENV_FILE:-.env.windkeep}\"",
        "COMPOSE_FILE=\"${COMPOSE_FILE:-compose.yaml}\"",
        "",
        "HTTP_CODE=$(curl -s -o /tmp/wk_response.json -w \"%{http_code}\" \\",
        "  -H \"Authorization: Bearer ${WINDKEEP_TOKEN}\" \\",
        "  \"${WINDKEEP_URL}/api/projects/${WINDKEEP_PROJECT_ID}/secrets\")",
        "",
        "if [ \"$HTTP_CODE\" != \"200\" ]; then",
        "  echo \"HTTP ${HTTP_CODE}:\" && cat /tmp/wk_response.json",
        "  exit 1",
        "fi",
        "",
        "umask 077",
        ": > \"$ENV_FILE\"",
        String.raw`while IFS=$'\t' read -r KEY VALUE; do`,
        "  # Escape backslashes and double-quotes for dotenv",
        String.raw`  ESCAPED=$(printf '%s' "$VALUE" | sed 's/\\/\\\\/g; s/"/\\"/g')`,
        String.raw`  printf '%s="%s"\n' "$KEY" "$ESCAPED" >> "$ENV_FILE"`,
        "done < <(jq -r '",
        "  .decryptedSecrets[] | . as $s | .values[] | [($s.key | ascii_upcase), .value] | @tsv",
        "' /tmp/wk_response.json)",
        "",
        "if [ ! -s \"$ENV_FILE\" ]; then",
        "  echo \"No secrets returned.\" && exit 1",
        "fi",
        "",
        "echo \"Wrote $(wc -l < \"$ENV_FILE\") secret(s) → $ENV_FILE\"",
        "docker compose -f \"$COMPOSE_FILE\" --env-file \"$ENV_FILE\" up \"$@\"",
        "",
        `# Project: ${projectId}`,
        `# WindKeep: ${baseURL}`,
      ].join("\n"),
    }),
  },
]
